import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <GoogleOAuthProvider clientId="803171903133-92r3ih0jjf8ftatohl6g9j8mq7mck9p9.apps.googleusercontent.com">
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              // Define default options
              className: '',
              duration: 5000,
              removeDelay: 1000,
              // style: {
              //   background: '#363636',
              //   color: '#fff',
              // },

              // Default options for specific types
              success: {
                duration: 5000,
                // iconTheme: {
                //   primary: 'green',
                //   secondary: 'black',
                // },
              },
            }}
          />
        </GoogleOAuthProvider>
      </body>
    </html >
  );
}
